### ISSUE TITLE
validate_gips breaks when log_posteriori is nan

### ISSUE THREAD

**Issue by MrDomani** [PrzeChoj/gips#31]
```{r}
library(gips)
library(rags2ridges)

GIPS_N_ITER <- 2

n_points <- 50
S <- createS(n=n_points, p=150)

D_coef <- 1000
delta <- 3

D_matrix <- diag(ncol(S)) * D_coef
g <- gips(S, n_points, delta = delta, D_matrix = D_matrix,
          was_mean_estimated = TRUE)
g_MAP <- find_MAP(g, max_iter = GIPS_N_ITER, return_probabilities = TRUE,
                  optimizer = "MH", save_all_perms = TRUE)
validate_gips(g_MAP)
```

**Comment by MrDomani** [comment]
Code above causes following error: 
```{r}
Error in if (!(abs(optimization_info[["best_perm_log_posteriori"]] - log_posteriori_of_gips(best_perm_gips)) <  : 
  missing value where TRUE/FALSE needed
```

**Comment by PrzeChoj** [comment]
The code above resulted in a `NaN` value, as You mentioned in #5. The `gips` v1.0.0 prints a warning in such a situation. This should be an Error.

It could be suboptimal because R already performed some calculations, but I think most of the time, the `NaN` here would be caused by the huge `ncol(S)` (over $500$), or huge `D_matrix` (as in the code above). In such situations, I think it should `NaN` itself quite quickly, i.e., in 1st iteration.

I made it throw an Error in 9e0d5ab155311171d656c0e21992a871c014b474.

Nevertheless, `gips` cannot process such a `gips` object yet. As mentioned in #5, I will try to push the boundary of `gips` performance there.
